apiVersion: v1
kind: Service
metadata:
  name: todo-app-project-svc
spec:
  type: NodePort
  selector:
    app: todo-app-project-movd
  ports:
    - name: http
      nodePort: 30080
      protocol: TCP
      port: 1234
      targetPort: 3000
